services:

  jupyter:
    build:
      context: .
      dockerfile:
        
        Dockerfile.jupyter-rocm-pt
        
    container_name: jupyter
    ports: 
      - "8888:8888"
    volumes:
      - ~/UC-NODE:/home/jovyan/work/UC-NODE
      - /mnt/data:/home/jovyan/data        
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/home/jovyan/work/UC-NODE
      - MLFLOW_TRACKING_URI=http://mlflow:8000
      - AMD_VISIBLE_DEVICES=all
      
      - HF_HOME=${HF_HOME}
      - HF_TOKEN_PATH=${HF_TOKEN_PATH}
      - HF_TOKEN=${HF_TOKEN}
      
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri   
    group_add:
      - ${GID_RENDER} 
    restart: always 
    shm_size: 2g

  mlflow:
    build:
       context: . 
       dockerfile: Dockerfile.mlflow
    container_name: mlflow
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${S3_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - AWS_REQUEST_CHECKSUM_CALCULATION=WHEN_REQUIRED
      - AWS_RESPONSE_CHECKSUM_VALIDATION=WHEN_REQUIRED  
    volumes:
      - /mnt/metrics:/mlflow/mlruns 
    command:
      - mlflow
      - server
      - --backend-store-uri=/mlflow/mlruns
      - --artifacts-destination=s3://UC-NODE-mlflow-artifacts
      - --serve-artifacts
      - --host=0.0.0.0
      - --port=8000